import type { ResearchReport, ResearchContext } from "@/types";

function confidenceColor(score: number): string {
  if (score >= 70) return "#15803d";
  if (score >= 50) return "#a16207";
  return "#b91c1c";
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : { r: 0, g: 0, b: 0 };
}

function sentimentColor(sentiment: string): string {
  switch (sentiment) {
    case "positive":
      return "#15803d";
    case "negative":
      return "#b91c1c";
    case "mixed":
      return "#a16207";
    default:
      return "#374151";
  }
}

export async function generatePDF(
  report: ResearchReport,
  context: ResearchContext
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = 210;
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = margin;

  const isAdrs = !!report.variantPerformance;

  const addPage = () => {
    doc.addPage();
    y = margin;
  };

  const addPageIfNeeded = (h: number) => {
    if (y + h > 275) addPage();
  };

  const writeHeading = (text: string, size = 14) => {
    addPageIfNeeded(12);
    doc.setFontSize(size);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(17, 24, 39);
    doc.text(text, margin, y);
    y += size * 0.45;
    doc.setDrawColor(79, 70, 229);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentW, y);
    y += 5;
  };

  const writeSubheading = (text: string) => {
    addPageIfNeeded(10);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.text(text, margin, y);
    y += 6;
  };

  const writeParagraph = (text: string, size = 9.5) => {
    if (!text) return;
    doc.setFontSize(size);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(31, 41, 55);
    const lines = doc.splitTextToSize(text, contentW);
    addPageIfNeeded(lines.length * size * 0.45 + 4);
    doc.text(lines, margin, y);
    y += lines.length * size * 0.45 + 4;
  };

  // ── Cover Header ──────────────────────────────────────────────────────────
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageW, 38, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("PRISM RESEARCH FINDINGS", margin, 16);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  if (isAdrs) {
    doc.text(
      "Adobe Express — Positioning Concept for India",
      margin,
      24
    );
  } else {
    doc.text("Synthetic User Research Report", margin, 24);
  }
  doc.setFontSize(8);
  doc.text(
    `Generated by PRISM (Primary Research and Insight Synthesis Model)  ·  ${new Date(
      report.generatedAt
    ).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    margin,
    32
  );

  y = 50;

  // ── Confidence Banner ─────────────────────────────────────────────────────
  const cs = report.confidenceScore;
  const csColor = confidenceColor(cs.score);
  const rgb = hexToRgb(csColor);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, contentW, 22, 3, 3, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(107, 114, 128);
  doc.text("CONFIDENCE SCORE", margin + 5, y + 7);
  doc.setFontSize(18);
  doc.setTextColor(rgb.r, rgb.g, rgb.b);
  doc.text(`${cs.score}/100`, margin + 5, y + 17);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);
  const csLines = doc.splitTextToSize(cs.reasoning, contentW - 50);
  doc.text(csLines, margin + 50, y + 8);
  y += 28;

  // ── Background ───────────────────────────────────────────────────────────
  if (report.background) {
    writeHeading("BACKGROUND");
    writeParagraph(report.background);
  }

  // ── Methodology ──────────────────────────────────────────────────────────
  writeHeading("RESEARCH OBJECTIVES & METHODOLOGY");
  writeParagraph(`Hypothesis: ${context.hypothesis}`);
  writeParagraph(report.methodologyNote);
  writeParagraph(
    `Method: ${
      report.researchMethod === "survey"
        ? "Synthetic survey, unmoderated"
        : "In-depth synthetic interview"
    } · Panel size: ${report.panelSize} respondents · Variant order: ${
      isAdrs ? "randomized per respondent" : "n/a"
    }`,
    8.5
  );

  // ── Participant Profile ──────────────────────────────────────────────────
  if (report.participantProfile) {
    addPageIfNeeded(40);
    writeHeading("PARTICIPANT PROFILE");

    const pp = report.participantProfile;
    writeSubheading("Audience Cohort Breakdown");

    // Cohort table
    addPageIfNeeded(pp.cohorts.length * 8 + 12);
    doc.setFillColor(243, 244, 246);
    doc.rect(margin, y, contentW, 7, "F");
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(75, 85, 99);
    doc.text("Cohort", margin + 3, y + 5);
    doc.text("N", margin + contentW - 50, y + 5, { align: "right" });
    doc.text("%", margin + contentW - 30, y + 5, { align: "right" });
    doc.text("Characteristics", margin + contentW - 25, y + 5);
    y += 7;

    doc.setFont("helvetica", "normal");
    pp.cohorts.forEach((c, i) => {
      addPageIfNeeded(8);
      if (i % 2 === 0) {
        doc.setFillColor(249, 250, 251);
        doc.rect(margin, y, contentW, 7, "F");
      }
      doc.setTextColor(31, 41, 55);
      doc.text(c.name, margin + 3, y + 5);
      doc.text(String(c.count), margin + contentW - 50, y + 5, { align: "right" });
      doc.text(`${c.percent}%`, margin + contentW - 30, y + 5, { align: "right" });
      doc.setFontSize(7.5);
      doc.setTextColor(107, 114, 128);
      const ch = doc.splitTextToSize(c.characteristics, 50);
      doc.text(ch[0] || "", margin + contentW - 25, y + 5);
      doc.setFontSize(8.5);
      y += 7;
    });
    y += 4;

    // Demographics row
    if (pp.meanAge || pp.medianAge) {
      addPageIfNeeded(12);
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(107, 114, 128);
      const demoText = [
        pp.meanAge ? `Mean age: ${pp.meanAge}` : "",
        pp.medianAge ? `Median: ${pp.medianAge}` : "",
      ].filter(Boolean).join("  ·  ");
      doc.text(demoText, margin, y);
      y += 6;
    }
  }

  // ── Executive Summary ───────────────────────────────────────────────────
  addPageIfNeeded(20);
  writeHeading("EXECUTIVE SUMMARY");

  writeSubheading("Top-line");
  writeParagraph(report.executiveSummary);

  if (report.qualitativeOverview) {
    writeSubheading("Qualitative Overview");
    writeParagraph(report.qualitativeOverview);
  }

  // ── Variant Performance Table ───────────────────────────────────────────
  if (report.variantPerformance) {
    addPageIfNeeded(40);
    writeSubheading("Quantitative Overview — Variant Performance");

    // Sort by avg rating desc
    const sortedVps = [...report.variantPerformance].sort(
      (a, b) => b.averageRating - a.averageRating
    );

    addPageIfNeeded(sortedVps.length * 10 + 14);
    doc.setFillColor(238, 242, 255);
    doc.rect(margin, y, contentW, 8, "F");
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(67, 56, 202);
    doc.text("RANK  VARIANT", margin + 3, y + 5.5);
    doc.text("AVG RATING", margin + contentW - 70, y + 5.5);
    doc.text("INTENT %", margin + contentW - 35, y + 5.5);
    y += 8;

    doc.setFont("helvetica", "normal");
    sortedVps.forEach((vp, i) => {
      addPageIfNeeded(10);
      if (i % 2 === 0) {
        doc.setFillColor(249, 250, 251);
        doc.rect(margin, y, contentW, 9, "F");
      }
      doc.setFontSize(9);
      doc.setTextColor(79, 70, 229);
      doc.setFont("helvetica", "bold");
      doc.text(`#${i + 1}`, margin + 3, y + 6);

      doc.setTextColor(31, 41, 55);
      doc.setFont("helvetica", "normal");
      const truncated = vp.variantText.length > 60 ? vp.variantText.slice(0, 58) + "…" : vp.variantText;
      doc.text(`"${truncated}"`, margin + 13, y + 6);

      doc.setFont("helvetica", "bold");
      doc.text(vp.averageRating.toFixed(2), margin + contentW - 70, y + 6);
      doc.setFont("helvetica", "normal");
      doc.text(`${Math.round(vp.interestPercent)}%`, margin + contentW - 35, y + 6);
      y += 9;
    });
    y += 4;
  }

  // ── Strategic Takeaways ─────────────────────────────────────────────────
  if (report.strategicTakeaways && report.strategicTakeaways.length > 0) {
    addPageIfNeeded(30);
    writeSubheading("Strategic Takeaways");
    report.strategicTakeaways.forEach((t, i) => {
      addPageIfNeeded(15);
      doc.setFontSize(9.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(17, 24, 39);
      const principleLines = doc.splitTextToSize(`${i + 1}. ${t.principle}`, contentW);
      doc.text(principleLines, margin, y);
      y += principleLines.length * 5 + 1;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(75, 85, 99);
      doc.setFontSize(8.5);
      const expLines = doc.splitTextToSize(t.explanation, contentW - 5);
      doc.text(expLines, margin + 5, y);
      y += expLines.length * 4 + 4;
    });
  }

  // ── Recommended Tagline ─────────────────────────────────────────────────
  if (report.adrsRecommendation) {
    addPageIfNeeded(40);
    doc.setFillColor(238, 242, 255);
    doc.roundedRect(margin, y, contentW, 35, 3, 3, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.text("RECOMMENDED TAGLINE", margin + 5, y + 6);
    doc.setFontSize(13);
    doc.setTextColor(17, 24, 39);
    doc.text(`"${report.adrsRecommendation.taglineText}"`, margin + 5, y + 14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const recLines = doc.splitTextToSize(
      report.adrsRecommendation.primaryRecommendation,
      contentW - 10
    );
    doc.text(recLines, margin + 5, y + 22);
    y += 40;

    if (report.adrsRecommendation.supportingFactors.length > 0) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(75, 85, 99);
      doc.text("Supporting factors:", margin, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(55, 65, 81);
      report.adrsRecommendation.supportingFactors.forEach((f, i) => {
        addPageIfNeeded(8);
        const fl = doc.splitTextToSize(`${i + 1}. ${f}`, contentW - 5);
        doc.text(fl, margin + 5, y);
        y += fl.length * 4.5 + 1.5;
      });
      y += 3;
    }
  }

  // ── Detailed Variant Analysis (one per variant) ─────────────────────────
  if (report.variantPerformance) {
    addPage();
    writeHeading("DETAILED VARIANT ANALYSIS");

    report.variantPerformance.forEach((vp, idx) => {
      addPageIfNeeded(60);

      doc.setFillColor(238, 242, 255);
      doc.rect(margin, y, contentW, 14, "F");
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(67, 56, 202);
      doc.text(`Variant ${idx + 1}`, margin + 4, y + 5.5);
      doc.setFontSize(10);
      doc.setTextColor(17, 24, 39);
      doc.text(`"${vp.variantText}"`, margin + 4, y + 11);
      y += 18;

      // Stats line
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(75, 85, 99);
      doc.text(
        `Average Rating: ${vp.averageRating.toFixed(2)}/5  ·  Interest to try: ${Math.round(vp.interestPercent)}%`,
        margin,
        y
      );
      y += 6;

      // Distribution
      const distText = vp.ratingDistribution
        .sort((a, b) => b.rating - a.rating)
        .map((r) => `${r.rating}: ${Math.round(r.percent)}%`)
        .join("  ·  ");
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text(`Distribution — ${distText}`, margin, y);
      y += 8;

      // Positive sentiment table
      writeSubheading("Top Positive Reactions");
      vp.topPositives.forEach((row) => {
        addPageIfNeeded(20);
        doc.setFillColor(240, 253, 244);
        const startY = y;
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(21, 128, 61);
        doc.text(`${row.category}  (${row.count} resp.)`, margin + 3, y + 4);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(34, 84, 61);
        const themeLines = doc.splitTextToSize(row.themes, contentW - 8);
        doc.text(themeLines, margin + 3, y);
        y += themeLines.length * 3.8 + 1;
        doc.setFont("helvetica", "italic");
        doc.setTextColor(80, 130, 90);
        doc.setFontSize(7.5);
        row.quotes.slice(0, 2).forEach((q) => {
          const ql = doc.splitTextToSize(`"${q}"`, contentW - 10);
          doc.text(ql, margin + 5, y);
          y += ql.length * 3.5 + 0.5;
        });
        const blockH = y - startY + 1;
        doc.setFillColor(240, 253, 244);
        doc.rect(margin, startY - 1, contentW, blockH, "S");
        y += 2;
      });

      // Negative sentiment table
      writeSubheading("Top Negative Reactions");
      vp.topNegatives.forEach((row) => {
        addPageIfNeeded(20);
        const startY = y;
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(185, 28, 28);
        doc.text(`${row.category}  (${row.count} resp.)`, margin + 3, y + 4);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(127, 29, 29);
        const themeLines = doc.splitTextToSize(row.themes, contentW - 8);
        doc.text(themeLines, margin + 3, y);
        y += themeLines.length * 3.8 + 1;
        doc.setFont("helvetica", "italic");
        doc.setTextColor(140, 60, 60);
        doc.setFontSize(7.5);
        row.quotes.slice(0, 2).forEach((q) => {
          const ql = doc.splitTextToSize(`"${q}"`, contentW - 10);
          doc.text(ql, margin + 5, y);
          y += ql.length * 3.5 + 0.5;
        });
        const blockH = y - startY + 1;
        doc.setFillColor(254, 242, 242);
        doc.rect(margin, startY - 1, contentW, blockH, "S");
        y += 2;
      });

      // Narrative
      addPageIfNeeded(15);
      writeSubheading("Analyst Narrative");
      writeParagraph(vp.narrative);
      y += 4;
    });
  }

  // ── Cross-Thematic Analysis ────────────────────────────────────────────
  if (report.crossThemes && report.crossThemes.length > 0) {
    addPageIfNeeded(30);
    writeHeading("CROSS-THEMATIC ANALYSIS");
    report.crossThemes.forEach((t) => {
      addPageIfNeeded(20);
      writeSubheading(t.title);
      writeParagraph(t.analysis);
    });
  }

  // ── Generic Key Findings (when no variants) ────────────────────────────
  if (!report.variantPerformance && report.keyFindings.length > 0) {
    addPageIfNeeded(20);
    writeHeading("KEY FINDINGS");
    report.keyFindings.forEach((f, i) => {
      addPageIfNeeded(25);
      doc.setFontSize(10.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(79, 70, 229);
      doc.text(`${i + 1}. ${f.theme}`, margin, y);
      y += 5.5;
      const sCol = sentimentColor(f.sentiment);
      const sRgb = hexToRgb(sCol);
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(sRgb.r, sRgb.g, sRgb.b);
      doc.text(`[${f.sentiment.toUpperCase()}]`, margin + 3, y);
      y += 4.5;
      doc.setTextColor(17, 24, 39);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      const sl = doc.splitTextToSize(f.summary, contentW - 4);
      doc.text(sl, margin + 3, y);
      y += sl.length * 4.5 + 2;
      f.evidence.slice(0, 3).forEach((ev) => {
        addPageIfNeeded(10);
        doc.setFontSize(8);
        doc.setTextColor(75, 85, 99);
        doc.setFont("helvetica", "italic");
        const evl = doc.splitTextToSize(`• "${ev}"`, contentW - 8);
        doc.text(evl, margin + 6, y);
        y += evl.length * 3.8 + 1;
      });
      y += 3;
    });
  }

  // ── Recommendations ─────────────────────────────────────────────────────
  addPageIfNeeded(30);
  writeHeading("RECOMMENDATIONS");
  report.recommendations.forEach((rec, i) => {
    addPageIfNeeded(15);
    doc.setFillColor(245, 245, 255);
    const recLines = doc.splitTextToSize(rec, contentW - 12);
    const boxH = recLines.length * 5 + 8;
    doc.roundedRect(margin, y - 2, contentW, boxH, 2, 2, "F");
    doc.setFontSize(9.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.text(`${i + 1}.`, margin + 4, y + 4);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(17, 24, 39);
    doc.text(recLines, margin + 10, y + 4);
    y += boxH + 3;
  });

  // ── Confidence Detail ───────────────────────────────────────────────────
  addPageIfNeeded(40);
  writeHeading("CONFIDENCE ANALYSIS");
  writeParagraph(cs.alignmentNotes);

  if (cs.strengthFactors.length > 0) {
    addPageIfNeeded(15);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(21, 128, 61);
    doc.text("Strength factors:", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(55, 65, 81);
    cs.strengthFactors.forEach((f) => {
      addPageIfNeeded(8);
      const fl = doc.splitTextToSize(`+ ${f}`, contentW - 4);
      doc.text(fl, margin + 4, y);
      y += fl.length * 4 + 1;
    });
    y += 3;
  }

  if (cs.limitationFactors.length > 0) {
    addPageIfNeeded(15);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(185, 28, 28);
    doc.text("Limitation factors:", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(55, 65, 81);
    cs.limitationFactors.forEach((f) => {
      addPageIfNeeded(8);
      const fl = doc.splitTextToSize(`− ${f}`, contentW - 4);
      doc.text(fl, margin + 4, y);
      y += fl.length * 4 + 1;
    });
    y += 3;
  }

  if (cs.biasFlags.length > 0) {
    addPageIfNeeded(15);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(161, 98, 7);
    doc.text("Bias flags:", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(55, 65, 81);
    cs.biasFlags.forEach((f) => {
      addPageIfNeeded(8);
      const fl = doc.splitTextToSize(`⚠ ${f}`, contentW - 4);
      doc.text(fl, margin + 4, y);
      y += fl.length * 4 + 1;
    });
    y += 3;
  }

  // ── Disclaimer ──────────────────────────────────────────────────────────
  addPageIfNeeded(20);
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(156, 163, 175);
  const disc =
    "Note: This report was generated using PRISM (Primary Research and Insight Synthesis Model), a synthetic user research tool. Panel responses are AI-simulated and should be validated with real user research before making major product decisions.";
  const dl = doc.splitTextToSize(disc, contentW);
  doc.text(dl, margin, y);

  // ── Footer on every page ────────────────────────────────────────────────
  const totalPages = (
    doc as unknown as { internal: { getNumberOfPages: () => number } }
  ).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(156, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("PRISM · Synthetic Research · Confidential", margin, 290);
    doc.text(`Page ${i} of ${totalPages}`, pageW - margin, 290, { align: "right" });
  }

  doc.save(`prism-report-${Date.now()}.pdf`);
}

export function generateMarkdown(
  report: ResearchReport,
  context: ResearchContext
): string {
  const date = new Date(report.generatedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const isAdrs = !!report.variantPerformance;
  const lines: string[] = [];

  lines.push("# PRISM RESEARCH FINDINGS");
  if (isAdrs) {
    lines.push("## Adobe Express — Positioning Concept Study");
  }
  lines.push("");
  lines.push(`**Generated by:** PRISM (Primary Research and Insight Synthesis Model)`);
  lines.push(`**Date:** ${date}`);
  lines.push(`**Confidence Score:** ${report.confidenceScore.score}/100`);
  lines.push(`**Method:** ${report.researchMethod === "survey" ? "Synthetic Survey" : "Synthetic Interview"} (${report.panelSize} respondents)`);
  lines.push("");
  lines.push("---");
  lines.push("");

  if (report.background) {
    lines.push("## BACKGROUND", "", report.background, "");
  }

  lines.push(
    "## RESEARCH OBJECTIVES AND METHODOLOGY",
    "",
    `**Hypothesis:** ${context.hypothesis}`,
    "",
    report.methodologyNote,
    ""
  );

  if (report.participantProfile) {
    lines.push("---", "", "## PARTICIPANT PROFILE", "");
    lines.push("| Cohort | # of Respondents | % | Key Characteristics |");
    lines.push("|---|---|---|---|");
    report.participantProfile.cohorts.forEach((c) => {
      lines.push(`| ${c.name} | ${c.count} | ${c.percent}% | ${c.characteristics} |`);
    });
    lines.push("");
    if (report.participantProfile.meanAge || report.participantProfile.medianAge) {
      lines.push("### Demographics");
      if (report.participantProfile.meanAge)
        lines.push(`- Mean age: ${report.participantProfile.meanAge}`);
      if (report.participantProfile.medianAge)
        lines.push(`- Median age: ${report.participantProfile.medianAge}`);
      lines.push("");
    }
  }

  lines.push("---", "", "## EXECUTIVE SUMMARY", "");

  if (report.variantPerformance) {
    lines.push("### Quantitative Overview", "");
    lines.push("**Tagline Performance by Average Resonance Rating:**", "");
    lines.push("| Rank | Variant | Avg Rating | Interest to Try |");
    lines.push("|---|---|---|---|");
    [...report.variantPerformance]
      .sort((a, b) => b.averageRating - a.averageRating)
      .forEach((vp, i) => {
        lines.push(
          `| #${i + 1} | "${vp.variantText}" | ${vp.averageRating.toFixed(2)} | ${Math.round(vp.interestPercent)}% |`
        );
      });
    lines.push("");
    lines.push(report.executiveSummary, "");
  } else {
    lines.push(report.executiveSummary, "");
  }

  if (report.qualitativeOverview) {
    lines.push("### Qualitative Overview", "", report.qualitativeOverview, "");
  }

  if (report.strategicTakeaways && report.strategicTakeaways.length > 0) {
    lines.push("### Strategic Takeaways", "");
    report.strategicTakeaways.forEach((t, i) => {
      lines.push(`${i + 1}. **${t.principle}** — ${t.explanation}`);
    });
    lines.push("");
  }

  if (report.adrsRecommendation) {
    lines.push("### Recommended Tagline", "");
    lines.push(`> **"${report.adrsRecommendation.taglineText}"**`, "");
    lines.push(report.adrsRecommendation.primaryRecommendation, "");
    if (report.adrsRecommendation.supportingFactors.length > 0) {
      lines.push("Supporting factors:");
      report.adrsRecommendation.supportingFactors.forEach((f, i) => {
        lines.push(`${i + 1}. ${f}`);
      });
      lines.push("");
    }
  }

  if (report.variantPerformance) {
    lines.push("---", "", "## DETAILED VARIANT ANALYSIS", "");
    report.variantPerformance.forEach((vp, idx) => {
      lines.push(`### Variant ${idx + 1}: "${vp.variantText}"`, "");
      lines.push(`**Average Rating:** ${vp.averageRating.toFixed(2)} / 5.0`);
      lines.push(`**Interest to Try App:** ${Math.round(vp.interestPercent)}%`);
      const dist = vp.ratingDistribution
        .sort((a, b) => b.rating - a.rating)
        .map((r) => `${r.rating} (${Math.round(r.percent)}%)`)
        .join("; ");
      lines.push(`**Response Distribution:** ${dist}`, "");

      lines.push("#### Top 3 Positive & Negative Sentiments", "");
      lines.push("| Feedback Type | Reason Category | # | Key Themes | Representative Quotes |");
      lines.push("|---|---|---|---|---|");
      vp.topPositives.forEach((row) => {
        const quotes = row.quotes
          .slice(0, 2)
          .map((q) => `"${q}"`)
          .join(" / ");
        lines.push(`| Positive | ${row.category} | ${row.count} | ${row.themes} | ${quotes} |`);
      });
      vp.topNegatives.forEach((row) => {
        const quotes = row.quotes
          .slice(0, 2)
          .map((q) => `"${q}"`)
          .join(" / ");
        lines.push(`| Negative | ${row.category} | ${row.count} | ${row.themes} | ${quotes} |`);
      });
      lines.push("", vp.narrative, "");
    });
  }

  if (report.crossThemes && report.crossThemes.length > 0) {
    lines.push("---", "", "## CROSS-THEMATIC ANALYSIS", "");
    report.crossThemes.forEach((t) => {
      lines.push(`### ${t.title}`, "", t.analysis, "");
    });
  }

  if (!report.variantPerformance && report.keyFindings.length > 0) {
    lines.push("---", "", "## KEY FINDINGS", "");
    report.keyFindings.forEach((f, i) => {
      lines.push(`### ${i + 1}. ${f.theme}`);
      lines.push(`*Sentiment: ${f.sentiment}*`, "", f.summary, "");
      lines.push("**Evidence:**");
      f.evidence.forEach((ev) => lines.push(`- "${ev}"`));
      lines.push("");
    });
  }

  lines.push("---", "", "## CONCLUSIONS & RECOMMENDATIONS", "");
  report.recommendations.forEach((r, i) => lines.push(`${i + 1}. ${r}`));
  lines.push("");

  lines.push(
    "---",
    "",
    "## CONTEXT & NEXT STEPS",
    "",
    "The findings above are based on AI-simulated synthetic respondents. They are directionally valuable for narrowing strategic options but should be validated with real user research before making major product decisions.",
    ""
  );

  lines.push(
    "---",
    "",
    "## CONFIDENCE ANALYSIS",
    "",
    `**Score:** ${report.confidenceScore.score}/100`,
    "",
    report.confidenceScore.reasoning,
    "",
    `**Market Alignment:** ${report.confidenceScore.alignmentNotes}`,
    ""
  );

  if (report.confidenceScore.strengthFactors.length > 0) {
    lines.push("**Strength Factors:**");
    report.confidenceScore.strengthFactors.forEach((f) => lines.push(`- ✓ ${f}`));
    lines.push("");
  }
  if (report.confidenceScore.limitationFactors.length > 0) {
    lines.push("**Limitation Factors:**");
    report.confidenceScore.limitationFactors.forEach((f) => lines.push(`- ✗ ${f}`));
    lines.push("");
  }
  if (report.confidenceScore.biasFlags.length > 0) {
    lines.push("**Bias Flags:**");
    report.confidenceScore.biasFlags.forEach((f) => lines.push(`- ⚠ ${f}`));
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "*Generated by PRISM. Panel responses are AI-simulated and should be validated with real user research before major product decisions.*"
  );

  return lines.join("\n");
}
